### ISSUE TITLE
Next.js + emotion Implementation

### ISSUE THREAD

**Issue by chulian1819** [tastejs/hacker-news-pwas#114]
no idea why this is not listed  
https://github.com/tkh44/next-hnpwa-guide-kit
demo  https://hnpwa.life

![image](https://user-images.githubusercontent.com/4574893/29805968-16f52088-8cd0-11e7-8d13-f8571ca8cef7.png)

**Comment by housseindjirdeh** [comment]
Apologies for not getting to this a lot sooner 😭 

Looks like we already a submission of the same name (`next-hnpwa-guide-kit`) but I agree, would love to see another one landed that includes Emotion! Happy to consider it's addition if the author feels like putting up a PR :)
