### ISSUE TITLE
HNPWA API Errors

### ISSUE THREAD

**Issue by kristoferbaxter** [tastejs/hacker-news-pwas#122]
I've found the HNPWA Api to fail at a significantly higher rate than expected as I've ported over implementations.

Here's an example URL which never resolves:
https://news.ycombinator.com/item?id=15480654
https://hnpwa.com/api/v0/item/15480654.json

And a few from server logs:
```
Error updating item: 15491775
Error updating item: 15480654
Error updating item: 15478546
Error updating item: 15490987
```

Are there plans to address this or should I work around them with an alternate API?

**Comment by davideast** [comment]
@kristoferbaxter I'll take a look. I know there can be permissions issues with comments and it causes the whole thing to fail.

**Comment by housseindjirdeh** [comment]
Closing this now, but please let me know if we should reopen this @davideast 🙌

**Comment by davideast** [comment]
That link worked now, so I'm hoping I fixed it 🤞
