### ISSUE TITLE
Adding Inferno Version

### ISSUE THREAD

**Issue by aretheregods** [tastejs/hacker-news-pwas#125]
Hello, HNPWA people. I opened a pull request [#121](https://github.com/tastejs/hacker-news-pwas/pull/121) to add an [Inferno](https://infernojs.org) implementation and hope I added and documented everything correctly. I wasn't sure about the weight property and might need guidance on the loading times. Please let me know anything else that needs to be looked at.

**Comment by chulian1819** [comment]
can you make it do server side rendering?

**Comment by kristoferbaxter** [comment]
Apologies for the delay. I'll take a look at this (and other new implementations) in the next day or two.

**Comment by aretheregods** [comment]
@kristoferbaxter That's awesome. Thanks.
@chulian1819 I can totally do that, but it'd be a different implementation then. I might build an ssr version if I can find the time, though. I **_am_** curious to see how much faster that would make it.

**Comment by housseindjirdeh** [comment]
Looks like this is in :) #121

So sorry for not getting to you sooner @aretheregods, and thanks a million for working on this 🙌
