### ISSUE TITLE
Use GitHub avatar images for authors instead of static check-in

### ISSUE THREAD

**Issue by addyosmani** [tastejs/hacker-news-pwas#13]
> Instead of including the images of the authors, how about we instead use their GitHub avatar image?

from @sindresorhus

**Comment by housseindjirdeh** [comment]
Already pushed an update to use each authors github avatar (for example: https://github.com/housseindjirdeh.png). 

Sorry for not being more clear in the PR ticket! If that looks good we should be able to close this.

**Comment by addyosmani** [comment]
Oh sweet. I totally missed https://github.com/tastejs/hacker-news-pwas/pull/11/commits/6780e7fd868f34ada31b7cf653a6752e1e7cf22e!
