### ISSUE TITLE
A new React HN implementation powered by react-server-renderer

### ISSUE THREAD

**Issue by JounQin** [tastejs/hacker-news-pwas#132]
Hey, I've just made an other react version of HNPWA powered by [react-server-renderer](https://github.com/JounQin/react-server-renderer).
Could anyone take a look? Thanks!

link:
https://react-hn.now.sh

lighthouse:
https://www.webpagetest.org/lighthouse.php?test=180101_2Y_84719548884ee4c268a559a36f513930&run=2

webpagetest (Regular 3g): https://www.webpagetest.org/result/180101_2Y_84719548884ee4c268a559a36f513930/

repository:
https://github.com/JounQin/react-hackernews

**Comment by housseindjirdeh** [comment]
Your submission is awesome, thank you so much 🚀 

Left a note on the PR about how we can explore options to improve the site. We can continue the discussion here whenever you get the chance 💬
