### ISSUE TITLE
create-react-app example is nonoptimal

### ISSUE THREAD

**Issue by stereobooster** [tastejs/hacker-news-pwas#137]
Hi. I checked given example with https://www.webpagetest.org (From: Dulles, VA - Moto G4 - Chrome - 3G). I'm talking about `stephenkingsley/hackerNews-pwa`.

https://www.webpagetest.org/result/180130_XR_657329befdfcd07c1712592b7455e092/

![waterfall](https://user-images.githubusercontent.com/179534/35589571-a1291bee-0604-11e8-8656-f05905fd16b4.png)

![filmstrip](https://user-images.githubusercontent.com/179534/35589582-a5adf68a-0604-11e8-839e-9428a13d90ef.png)

I fixed some issues in [round-1](https://github.com/stereobooster/hackerNews-pwa/tree/round-1):
- removed unnecessary images (logo and gif loader)
- `rel=preconnect`

https://www.webpagetest.org/result/180130_HR_894b9a821e6b53d0f4e2369fa00abfb3/

![waterfall](https://user-images.githubusercontent.com/179534/35590428-25d51b48-0607-11e8-8f38-977d29fae4a6.png)

![filmstrip](https://user-images.githubusercontent.com/179534/35590432-28df934a-0607-11e8-9037-2e274f893526.png)

I added even more optimisation, but those changes have a lot of bugs ([round-2](https://github.com/stereobooster/hackerNews-pwa/tree/round-2))
- switch from external API to API hosted on the same domain
- replaced `react` with `preact-compat` (without ejecting)
- partially prerendered page with `react-snap` (rendered shell and inlined CSS)
- `rel=preconnect`
- `rel=preload`

https://www.webpagetest.org/result/180130_D9_369033210c83432fd7ddee829836a232/

![waterfall](https://user-images.githubusercontent.com/179534/35591907-c4ff40a0-060b-11e8-994b-ac781339b0d0.png)

![filmstrip](https://user-images.githubusercontent.com/179534/35591992-f93a8348-060b-11e8-9879-bbb5721ec085.png)

Just saying CRA can do much better (even without SSR)

**Comment by housseindjirdeh** [comment]
Firstly, so sorry for not responding much sooner @stereobooster. We're now getting back on track resolving issues and submissions.

This is great!! We've set some base [requirements](https://github.com/tastejs/hacker-news-pwas#specification) for submissions but are always looking to find performance optimizations. Have you considered submitting PRs to the repository for this submission to improve it? I'm sure the author would love to have them included.

This also looks like a great example resource of when to use `react-snap` (it's a great tool!). For that reason I wouldn't mind landing this improved application as a separate submission if you prefer that as well.

Will close this issue for now but please don't hesitate to let me know what you think.
