### ISSUE TITLE
First example app not loading correctly

### ISSUE THREAD

**Issue by jumpalottahigh** [tastejs/hacker-news-pwas#138]
![image](https://user-images.githubusercontent.com/4155121/35815500-4c01627e-0aa1-11e8-891a-c39760e49da5.png)

To replicate: go to: https://hnpwa.com/ and scroll past the first 2 sections.

**Comment by usm4n** [comment]
@jumpalottahigh there is a pending pull request (#135) that addresses this issue, hopefully this will be fixed after the merge.

**Comment by kristoferbaxter** [comment]
Merged.

**Comment by jumpalottahigh** [comment]
Awesome, sorry for the extra issue.
