### ISSUE TITLE
Setup domain

### ISSUE THREAD

**Issue by addyosmani** [tastejs/hacker-news-pwas#15]
Need to get this routing over to the hosted site. @housseindjirdeh would you mind if we tried deploying this over to App Engine? We get whitelisted support/free hosting for projects like this there.

**Comment by addyosmani** [comment]
@housseindjirdeh @sindresorhus I've just setup a new whitelisted App Engine account called `hnpwa-prod` and added you both as co-owners 🙃   

Would we be okay with deploying the site directory there? I can get the domain pointing to it once it's up.

**Comment by housseindjirdeh** [comment]
Woohoo thanks a million @addyosmani, appreciate you adding us as co-owners :)

Absolutely I think it'll be perfect if we deploy it there!

**Comment by housseindjirdeh** [comment]
https://hnpwa-prod.appspot.com/

It's deployed! Now it should be a matter of just mapping the domain to the instance. I've set up #20 to track setting up a CI for the builds.

**Comment by addyosmani** [comment]
Domain setup. I'll update the repo summary with a link to it after some further testing is done. Might need to setup Cloudflare to get SSL on there too.
