### ISSUE TITLE
benchmark rounds

### ISSUE THREAD

**Issue by MatheusRV** [tastejs/hacker-news-pwas#150]
is possible to implement benchmark rounds to this?

**Comment by addyosmani** [comment]
@MatheusRV Could you expand on what you mean by "benchmark rounds"?

**Comment by housseindjirdeh** [comment]
We're in the process of clearing all issues that aren't being resolved (and sorry for not getting back to you sooner @MatheusRV!). I'll close this now but more than happy to reopen this if you still wish to explore adding this to the site.
