### ISSUE TITLE
Update SvelteJS in the README

### ISSUE THREAD

**Issue by addyosmani** [tastejs/hacker-news-pwas#17]
Live: https://hn.svelte.technology/
WPT: https://www.webpagetest.org/result/170503_5V_d258dea5b63fa104d2697d17de5bd8c6/

from https://github.com/tastejs/hacker-news-pwas/issues/7#issuecomment-298909723

**Comment by addyosmani** [comment]
3G fresh run: https://www.webpagetest.org/result/170503_JV_58596b51e40c5a3e0e0a7eec1738af08/ (TTI:  2s)

EM fresh run:
https://www.webpagetest.org/result/170503_YQ_c987af45e51612be3320dd87500beae8/ (TTI: 2.3s)

@Rich-Harris styling appears to be a little broken atm on the current deploy:

![image](https://cloud.githubusercontent.com/assets/110953/25686284/00574762-3022-11e7-9ff9-3bd36e17ca30.png)

is it just me or a known issue? (WPT can't seem to fetch styles either) 🙃

**Comment by Rich-Harris** [comment]
Whoops! Fixed, thanks — had the wrong `dist` folder included 😵

**Comment by addyosmani** [comment]
Thanks! No worries :)

**Comment by addyosmani** [comment]
New run on EM: https://www.webpagetest.org/result/170506_CY_60f3658fb6ca1c3c8426feccc631bfe8/ tti 3.6s

New run on fast 3G:
https://www.webpagetest.org/result/170506_9H_40a4c53f3f07b983e44feb518271d8a7/ tti 2.2s

@Rich-Harris those seem about right?

**Comment by Rich-Harris** [comment]
More or less, yep 👍
