### ISSUE TITLE
Add specifications/requirements to site

### ISSUE THREAD

**Issue by housseindjirdeh** [tastejs/hacker-news-pwas#18]
The site should link to the [specifications](https://github.com/tastejs/hacker-news-pwas#specification) required for each implementation (especially if we plan on making things [more standardized](https://github.com/tastejs/hacker-news-pwas/issues/7#issuecomment-298913589)).

Possible solutions:
1. Link to the README section in the website
2. Create a dedicated file (`SPECS.md`?) and link to it in the README as well as the site

**Comment by addyosmani** [comment]
After chatting we're happy with how this shows up on the site today.
