### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by housseindjirdeh** [tastejs/hacker-news-pwas#20]
Now that the site is deployed on App Engine (https://hnpwa-prod.appspot.com/), we probably want to set up a CI. Travis CI has some [neat documentation](https://docs.travis-ci.com/user/deployment/google-app-engine) with App Engine.

Moreover, here's a [gem](https://github.com/jamesramsay/jekyll-app-engine) I used to generate all the `app.yaml` handlers with Jekyll. Can make things a lot simpler for deploying so I think it makes sense to include it in the site with this ticket.

**Comment by addyosmani** [comment]
Would it be possible to commit your `https://github.com/jamesramsay/jekyll-app-engine` setup to the site directory? I tried deploying latest today but wasn't quite sure the best way to set it up to stay in sync with how you were using it :) :)

**Comment by housseindjirdeh** [comment]
Oops my apologies, should have gotten that to you sooner so you can easily deploy. Just submitted #22 for that (along with all the steps I used to deploy 😄 )

**Comment by housseindjirdeh** [comment]
@addyosmani don't know this is only coming to me now :sweat_smile: but I can only set up a Travis CI pipeline if I have admin access to the repo.

If you can't give me admin access, that's perfectly fine. Anyone with access to both the Google Cloud console  + this repo can just follow the instructions [here](https://docs.travis-ci.com/user/deployment/google-app-engine) to get the builds up and running.

**Comment by addyosmani** [comment]
Added admin privs ⭐️

**Comment by addyosmani** [comment]
and thanks for deploying!
