### ISSUE TITLE
Upgrade to be a PWA

### ISSUE THREAD

**Issue by addyosmani** [tastejs/hacker-news-pwas#21]
Adding SW caching should be all that is left now.

**Comment by chrisdwheatley** [comment]
Any suggestions on the best way to approach this?

I can write a basic SW which is fairly hardcoded and will need the cache version updating on each new release or I can try and create or hook into some pipeline and use `sw-precache` to handle everything.

**Comment by addyosmani** [comment]
I could see something using `sw-precache` that we run after the jekyll build process completes giving folks a relatively useful level of SW caching. Any help at all with this would be massively appreciated, @chrisdwheatley <3

**Comment by addyosmani** [comment]
@chrisdwheatley Do you think you might have time to take a look at this in the coming days? I'd like to shoot for having the site be a PWA (per Lighthouse) by Wednesday this week. Happy to work on the patch myself but if you have time more than happy for you to hack on it. Let us know ❤️

**Comment by chrisdwheatley** [comment]
Sure, will take a look tomorrow and report back my progress asap.

**Comment by addyosmani** [comment]
Thank you, kindly!

**Comment by chrisdwheatley** [comment]
Just pushed #27 to address this. Feedback appreciated.
