### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by addyosmani** [tastejs/hacker-news-pwas#26]
ID: UA-99127594-1

```html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-99127594-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by housseindjirdeh** [comment]
Analytics is already set up pretty much, we just need to add the ID to the config file as a`google_analytics` field and make sure the builds are done with `JEKYLL_ENV=production`

Once #27 is merged I'll do those changes and push it up (since there'll most likely be conflicts in `travis.yml`)
