### ISSUE TITLE
WebComponents implementation

### ISSUE THREAD

**Issue by CaptainCodeman** [tastejs/hacker-news-pwas#41]
FYI: I started working on a pure WebComponent only implementation (no-framework, just polyfills when required).

I'll send a PR to close this when it's done.

**Comment by CaptainCodeman** [comment]
This is work in progress (so forgive the rough edges / save your laughter) but it's here for now:

Preview: https://hn-dot-captain-codeman.appspot.com/
Source: https://github.com/CaptainCodeman/hn-webcomponents

Any ideas or suggestions welcome. Still experimenting with some things.

**Comment by housseindjirdeh** [comment]
This is an awesome start mate! Once routing + the rough edges are sorted out, I think this will be a great addition. Excited to see it come together as you work out the details 👍🏾

**Comment by housseindjirdeh** [comment]
Friendly ping @CaptainCodeman :) 

Did you happen to get some progress on this implementation? Will close this ticket for now but please let us know if you start getting some traction with this and we can reopen it!

**Comment by CaptainCodeman** [comment]
I had to put it on the back-burner while I worked on other things but hope to finish it off when I have some free time (never enough).

I was kind of hoping the HTML / CSS standardization might happen at some point.

**Comment by housseindjirdeh** [comment]
We haven't gotten to laying down specific standardization requirements unfortunately but hopefully we can have that discussion sometime soon.

Understood, there's never enough time to work on everything we want (trust me I know this too well :)). Take as long as you need mate, happy to continue this discussion when you manage to find some time in the near future.
