### ISSUE TITLE
Add React-HN (port of Preact-HN)

### ISSUE THREAD

**Issue by kristoferbaxter** [tastejs/hacker-news-pwas#43]
Repo: https://github.com/kristoferbaxter/react-hn

All the details are the same as the Preact version, but it uses React and React Router.

Lighthouse/Webpage Test: https://www.webpagetest.org/result/170522_PN_86f54c759ef3ac8ee1cdc7cb8f62528f/

**Comment by addyosmani** [comment]
Awesome. That would make adding it into #42 pretty straight-forward. @housseindjirdeh as an FYI that we also have info on the details if we want to try landing this as part of #42.

**Comment by housseindjirdeh** [comment]
Sweet should be able to get that in #42 today, @kristoferbaxter would we happen to have a Faster 3G WPT as well?

Let me know how you folks would like to continue naming when we begin to include multiple apps with the same name (commented about that in [42](https://github.com/tastejs/hacker-news-pwas/pull/42#issuecomment-303461942)) CC @addyosmani

**Comment by kristoferbaxter** [comment]
3G WPT: https://www.webpagetest.org/result/170523_6T_1C6B/
3G Fast WPT: https://www.webpagetest.org/result/170523_JN_1CAH/

**Comment by housseindjirdeh** [comment]
Included in #42

**Comment by addyosmani** [comment]
Awesome. Thanks, @kristoferbaxter and @housseindjirdeh! This has now landed 🎉
