### ISSUE TITLE
Ember.js implementation (WIP)

### ISSUE THREAD

**Issue by ivanvanderbyl** [tastejs/hacker-news-pwas#44]
I've put together an Ember.js implementation at [hackernews.io](https://hackernews.io)
Source: [ivanvanderbyl/ember-hackernews-pwa](https://github.com/ivanvanderbyl/ember-hackernews-pwa)

It's still a WIP, feedback very welcome. I'm working on page load performance and increasing the Lighthouse score (currently 82/100) before submitting a PR.

- [Web Page Performance Test result](https://www.webpagetest.org/result/170523_QE_fc0bf5994d8765fa5002410913b8de76/)

It implements all other required features in the HNPWA Spec.

There's still a [few outstanding items](https://github.com/ivanvanderbyl/ember-hackernews-pwa/issues/1) I need to get through before this will pass the performance test.

**Comment by cheeaun** [comment]
Got to say, that is a very cool domain.

**Comment by ivanvanderbyl** [comment]
@cheeaun thanks, had it sitting around for a few years. Thanks for providing an API to put it to proper use 😄

**Comment by addyosmani** [comment]
That is one sweet domain name. Thanks for filing an issue to help track the Ember implem, @ivanvanderbyl! Looks like it's coming together well.

It would be great if you could use webpagetest.org/easy to measure how well the app does on 3G and EM as our entries include tests for both of those when listing too.

**Comment by CaptainCodeman** [comment]
Good job, looks nice - like the comment links.

**Comment by addyosmani** [comment]
Btw there's another Ember implementation in PR form over at https://github.com/tastejs/hacker-news-pwas/pull/54. We welcome multiple implementations so still very interested in seeing your version come together @ivanvanderbyl.

**Comment by ivanvanderbyl** [comment]
Thanks for the heads up @addyosmani, I just added a proper PR for my implementation. I've done some byte shaving to reduce rendering time by about 20%. Just waiting for WPT to come back online before I have all the reports.

**Comment by housseindjirdeh** [comment]
Closing this as we landed it some time ago :)
