### ISSUE TITLE
Why vue seems slower than polymer?

### ISSUE THREAD

**Issue by muhajirframe** [tastejs/hacker-news-pwas#45]
I am comparing the speed of polymer and vue, it seems like polymer and much more faster. 

Its not just the first paint / interative. I mean when i am clicking around, polymer responds faster. How it could be? Is the implementation different?

**Comment by CaptainCodeman** [comment]
Using different frameworks would mean the implementations could be significantly different, even if they utilise similar technologies underneath.

**Comment by chrisdwheatley** [comment]
As @CaptainCodeman mentioned, there can be differences in server infrastructure, patterns used and much more between each implementation meaning these examples shouldn't be used as comparisons between JavaScript frameworks.

There's some great work going on in #42 which will make it clearer how each application is architected and what patterns and technologies are used.

**Comment by addyosmani** [comment]
The above answers are indeed correct. The Polymer implementation is using HTTP/2 Server Push, edge-caching and more aggressive code-splitting which combined together have an impact on the over time to interactivity of that implementation. Some of these concepts are also why the Preact implementation is also faster here. 

I might suggest opening up an issue on the Vue HN repo about adding support for HTTP/2 Server Push as it would be interesting to see what impact that has on performance.
