### ISSUE TITLE
[suggestion] Properly size images

### ISSUE THREAD

**Issue by mhadaily** [tastejs/hacker-news-pwas#53]
Hi @addyosmani , 

Website looks pretty good and fast on mobile, however, these are opportunities to optimize images in order to speed up loading. it's possible to consider smaller images for mobile and using different methods which is so-called [responsive images ](https://developers.google.com/web/fundamentals/design-and-ui/responsive/images#images_in_markup).  It will increase performance score on Lighthouse as well. 

If it seems ok, I am happy to help. 
The Best

**Comment by addyosmani** [comment]
> it's possible to consider smaller images for mobile and using different methods which is so-called responsive images . It will increase performance score on Lighthouse as well.

Did you have some specific suggestions in mind? On mobile right now we don't show the preview images for implementations at all to keep the page lightweight. Were you thinking logos and avatars or something else?

**Comment by mhadaily** [comment]
Although we are not showing preview images on Mobile, it seems they are still downloading.
http://hnpwa.s3-website-us-west-1.amazonaws.com/hnpwa.com.html

https://ibb.co/dWKTna
https://ibb.co/b1wKtF

> Were you thinking logos and avatars or something else?
Yes,  Logos and Avatars can be smaller while loading on mobile

You may close this topic if it's not necessary.

Thank you.

**Comment by housseindjirdeh** [comment]
Thanks for logging this @mhadaily :)

Will close this now but please feel free to continue the discussion if you really feel like we can leverage responsive images with `srcset` for the logos and avatars. Will be happy to reopen this and implement it if we all feel like it's something we should include 🙌
