### ISSUE TITLE
MithrilJs implementation

### ISSUE THREAD

**Issue by gyandeeps** [tastejs/hacker-news-pwas#56]
I have started working on [MithrilJs](https://mithril.js.org/) implementation of hacker news.

Source: https://github.com/gyandeeps/mithril-hn

* Using client side render
* I think I have covered all  the features/specifications as listed on this repo.
* Cleaning up stuff right now
* Working through webpagetest
* Need to get a permanent domain.

So far Emerging market Webpagetest results: https://www.webpagetest.org/result/170603_HQ_560dfc0f9ab171316f289f0aa508e266/

**Comment by addyosmani** [comment]
Nice work, @gyandeeps! Thanks for the contribution. Let's take a look: 

**Interactive in close to 5s:**

> https://www.webpagetest.org/lighthouse.php?test=170603_HQ_560dfc0f9ab171316f289f0aa508e266&run=1

Seeing 5.6s for EM and not far off for faster 3G. This looks pretty decent.

**Lighthouse score over over 90:**

You've got that covered on EM. 

**UX review:**

The deployment at https://mithril-hn-namndvkbkh.now.sh appears to have been up but is now down. Would it be possible to redeploy?

**Comment by gyandeeps** [comment]
Thanks for the review.
I haven't bought a permanent domain yet, i am just using the free version from now.sh which changes on every deploy. I keep the url updated on my repo -> https://github.com/gyandeeps/mithril-hn

**Comment by chrisdwheatley** [comment]
You can set an alias with `now` to have a more permanent domain name.

E.g. `now alias <deploy-id> mithril-hn` which will push your deploy to https://mithril-hn.now.sh

**Comment by addyosmani** [comment]
That's a useful tip @chrisdwheatley 👍 

@gyandeeps Feel free to keep us looped in as you work towards PR'ing in an entry for the app.

**Comment by housseindjirdeh** [comment]
We have a PR up for this implementation. Closing this issue since we can keep the discussion there 🕺
