### ISSUE TITLE
Does the Preact version actually qualify as SSR?

### ISSUE THREAD

**Issue by yyx990803** [tastejs/hacker-news-pwas#58]
The Preact version (and the alternative React impl. by @kristoferbaxter) seems to only server-render the application shell - the news items are dynamically rendered and not part of the initial HTML response. While there is some SSR involved, I think it's somewhat misleading to consider them "SSR: yes" compared to the Vue/Viper implementations where all news items are rendered on initial paint. (The Svelte version also seems to do full SSR but it's currently down so I can't check)

Maybe we should differentiate the SSR types into:

- None
- Shell only
- Full

**Comment by kristoferbaxter** [comment]
I'm slightly confused by this. Both the Preact implementation and React ones do render news items on the server.

if you're seeing an issue with the SSR please file a ticket for this to get addressed.

As for the clarification on type of SSR, I agree.

**Comment by yyx990803** [comment]
@kristoferbaxter inspecting the network requests, the initial response HTML contains only the top navigation shell and the SVG logo:

<img width="924" alt="screen shot 2017-06-05 at 8 42 20 am" src="https://cloud.githubusercontent.com/assets/499550/26766796/eed3fd2e-49ca-11e7-971a-12fa47bb5c37.png">

**Comment by kristoferbaxter** [comment]
Here's a curl for a user who has never visited (no service worker is installed).

```curl 'https://hn.kristoferbaxter.com/' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.8' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3108.0 Mobile Safari/537.36' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H 'cache-control: max-age=0' -H 'authority: hn.kristoferbaxter.com' -H 'cookie: __utma=221487938.1928966684.1490155329.1492925789.1492987421.8; __utmz=221487938.1492925789.7.2.utmcsr=github.com|utmccn=(referral)|utmcmd=referral|utmcct=/; __cfduid=d091063ee6e0e6e48159efde684fb1fe51496559022' --compressed```

You can test this behaviour by forcefully unregistering the service worker, disabling Javascript, and requesting a new document from 'https://hn.kristoferbaxter.com'.

<img width="932" alt="screen shot 2017-06-04 at 6 06 52 pm" src="https://cloud.githubusercontent.com/assets/61764/26767034/a572510a-4950-11e7-9e92-a488553a960f.png">

You'll should in this case (first visit) receive an entire document including stories, and the application is completely usable without scripting.

If you then re-enable Javascript and visit again, you should now begin to experience a progressive enhancement approach.... adding the service worker and becoming a single page application.

Subsequent visits after a worker is installed will automatically use the '/shell' path for document requests no matter the actual requested url in the main thread.

**Comment by kristoferbaxter** [comment]
Here's a screenshot of SSR content for the initial visit from devtools.

<img width="573" alt="screen shot 2017-06-04 at 6 10 22 pm" src="https://cloud.githubusercontent.com/assets/61764/26767078/2ab60ab4-4951-11e7-895b-65290b1ccae8.png">

**Comment by yyx990803** [comment]
Ah interesting, didn't realize it behaves differently depending on SW availability! Thanks for clarifying.
