### ISSUE TITLE
Can't retrieve Interactive times with Angular HN

### ISSUE THREAD

**Issue by housseindjirdeh** [tastejs/hacker-news-pwas#70]
Something that I've noticed recently with the [most recent commit](https://github.com/housseindjirdeh/angular2-hn/commit/0d78708bc79c24c86569522a470776da7a477bec) to Angular HN is that interactive times fail to generate in Lighthouse through WPT.

![image](https://user-images.githubusercontent.com/12476932/27015745-76c9e900-4ee4-11e7-8fb6-093649f43059.png)

The app now loads a single `async` bundle and I assume that's what might be causing the tests to fail 🤔 But I'm really not sure --> would appreciate any input you may have on why you might think it's happening. (Note this only happens with Lighthouse through WPT, running browser LH tests work just fine).

WPT: https://www.webpagetest.org/lighthouse.php?test=170612_Z6_aa9071abfe3da23088b08658d5758165&run=2

CC @kristoferbaxter

**Comment by addyosmani** [comment]
Raised this upstream with the Lighthouse team. Apparently it's one of the
TTI bugs they're aware of and are going to look at.

cc @patrickhulce in case this isn't covered in an open bug we can track
already (I don't think the PO fix helps with this one but could be wrong).

**Comment by patrickhulce** [comment]
@addyosmani this should have been fixed by https://github.com/GoogleChrome/lighthouse/pull/2300 and https://github.com/GoogleChrome/lighthouse/pull/2347, when WPT updates to 2.1.0 it should pick up the fix

the latest run for that URL
![image](https://user-images.githubusercontent.com/2301202/27019703-a88c5648-4eef-11e7-9084-3c74db075e31.png)

**Comment by addyosmani** [comment]
@patrickhulce Thanks so much for the quick reply and verifying! @pmeenan do you know if WebPageTest is going to be picking up the 2.1.0 update to Lighthouse in the coming weeks?

**Comment by pmeenan** [comment]
Should be live now. The npm update hoops for going from major to major apparently didn't help with minor version updates.  It should auto-update again now (I checked and all of them are on 2.1.0).

**Comment by addyosmani** [comment]
@pmeenan You rock. Thanks so much for checking the updates bumped what's live to latest LH.

**Comment by addyosmani** [comment]
Hmm. Just tried running two runs from /easy with Lighthouse checkbox enabled:

Faster 3G: https://www.webpagetest.org/result/170612_PP_423a2a0c8a02c22caab8759290ea08c0/

EM:
https://www.webpagetest.org/result/170612_FD_91fd67ca6fdd4cfb987643f96af6650d/

and manually with the Lighthouse checkbox on in advanced:

https://www.webpagetest.org/result/170612_FD_91fd67ca6fdd4cfb987643f96af6650d/

For some reason the Lighthouse report is no longer showing up in these. @pmeenan is that just me or are you seeing that too?

**Comment by pmeenan** [comment]
I'm seeing it too.  The log shows that LH thinks it is writing the reports but the files actually have different names:

```
  Printer html output written to /home/pmeenan/wptagent/work/Test/170612_ZG_021cfb79da75c2b655438dd0004d376a.1.0/lighthouse.report.html +43ms
  Printer json output written to /home/pmeenan/wptagent/work/Test/170612_ZG_021cfb79da75c2b655438dd0004d376a.1.0/lighthouse.report.json +19ms
```

```
Storing lighthouse.html.gz (81192 bytes)
Storing lighthouse.json.gz (38623 bytes)
```

I can have the agent monkey-patch the files back to the requested names but it looks like it might be a LH bug in 2.1.0 @patrickhulce

**Comment by pmeenan** [comment]
Looks like the json structure changed.  Updating the UI to pull the score from the new location now.

**Comment by pmeenan** [comment]
OK, should be fixed now (the previous tests should show it as well).

**Comment by housseindjirdeh** [comment]
It looks good now! 🎉 

https://www.webpagetest.org/lighthouse.php?test=170612_QV_9893ebcfb8b2efdf278051fd86fa3915&run=2

Cheers thanks so much for looking into this @pmeenan, really appreciate it :)

**Comment by patrickhulce** [comment]
Ah yeah sorry for the lack of heads up @pmeenan! Aggregations and the old report were deprecated v2 and removed v2.1, err not-so-semver

**Comment by addyosmani** [comment]
@housseindjirdeh Would you like to add some commits updating the WPT links for the Angular app?

Thanks once again, @pmeenan and @patrickhulce!

**Comment by housseindjirdeh** [comment]
@addyosmani put up a PR updating the Angular numbers: #72 :man_dancing:
