### ISSUE TITLE
Expand footer

### ISSUE THREAD

**Issue by housseindjirdeh** [tastejs/hacker-news-pwas#78]
<img width="1440" alt="screen shot 2017-06-21 at 1 30 48 am" src="https://user-images.githubusercontent.com/12476932/27368572-5dae214a-5621-11e7-9689-d1e65725cff5.png">

Since we're getting so many awesome contributions :tada:, the footer is started to look a bit squeezed :P

Wrapping to two rows will probably be the easiest solution - will put up a PR for this within the next few days

**Comment by addyosmani** [comment]
👍 Definitely down with switching to a two row layout for the footer.

**Comment by housseindjirdeh** [comment]
Closing since this is merged in 🎉 🎉🎉🎉
