### ISSUE TITLE
Help with Lighthouse scores - Audit error: The main thread was busy for the entire trace recording. 

### ISSUE THREAD

**Issue by mstijak** [tastejs/hacker-news-pwas#82]
I'm trying to get performance scores for my [CxJS based HN app](https://github.com/codaxy/cxjs-hackernews), but Lighthouse consistently reports: 
```
Audit error: The main thread was busy for the entire trace recording. First Interactive requires the main thread to be idle for several seconds.
```

The test results show somewhat idle thread after 2.5s. On my computer Lighthouse consistently outputs performance score above 90. 

https://www.webpagetest.org/result/170625_AT_2c86c9ee54229dc9d1e43f92367091b1/1/details/#waterfall_view_step1

I'm wondering if any of you experienced the same problem and if you have any advice to share.

**Comment by addyosmani** [comment]
We've run into a few situations where Lighthouse on WebPageTest is failing to correctly record during the trace. I just kicked off a fresh run at https://www.webpagetest.org/result/170630_PB_c41b524e1931aafc6e1598d4dfe5676e/ to see if this is a consistent issue with this particular app.

**Comment by mstijak** [comment]
Thanks for checking this out. 

I run the test at least 20 times and it's always the same result. 

This seems to be related to Firebase API, so I'll probably switch to node-hnapi for initial load...

**Comment by housseindjirdeh** [comment]
Feel like this might been corrected in a previous Lighthouse build but I'm not sure. However doing a few runs on your app and things look smooth so I'll close this ticket. Please feel free to continue the discussion if you're still experiencing this however!
