### ISSUE TITLE
Glimmer.js Implementation 

### ISSUE THREAD

**Issue by mhadaily** [tastejs/hacker-news-pwas#83]
Hi, 
spent some time and implemented hackernews PWA with GlimmerJs.

Link: https://glimmer-hn-pwa.firebaseapp.com/

1- [WebPageTest Result](https://www.webpagetest.org/result/170708_34_1ae3fbe0c7f0f90ad0b46282ab2ce5a5/)

2- [LightHouse Result](https://glimmer-hn-pwa.firebaseapp.com/lighthouse.html)

3- [Repo: https://github.com/mhadaily/glimmer-hn-pwa](https://github.com/mhadaily/glimmer-hn-pwa)

Framework/UI libraries: Glimmer.js, Navigo  
Module bundling: Ember (Rolleup, Brocoli)
Service Worker: ESW
Performance patterns: HTTP/2 with Server Push
Hosting: Firebase

**Comment by addyosmani** [comment]
✔️ interactive over 3G/Moto G4 in under 5 seconds
✔️ Over 90/100 on Lighthouse

Some very minor layout bugs:
https://glimmer-hn-pwa.firebaseapp.com/#/item/14652993

I would suggest changing the Glimmer.js text to Glimmer HN (or something that calls out the name of this app vs the framework/library used to build it)

@mhadaily Do you want to go ahead and file a PR once the above two are addressed?

**Comment by mhadaily** [comment]
> @mhadaily Do you want to go ahead and file a PR once the above two are addressed?

@addyosmani Yes, I'll fix and send a PR today. Thanks for the suggestion.

**Comment by housseindjirdeh** [comment]
Closing this since it's merged in :)

Great work @mhadaily - app looks beautiful 🎉
