### ISSUE TITLE
Fast 3G misnamed?

### ISSUE THREAD

**Issue by lukeed** [tastejs/hacker-news-pwas#9]
Looking through the results, I got the impression that all of the "_Fast 3G_" times were using WPT's "Fast 3G" setting. Even though the regular 3G _is_ faster than the 3GEM setting, it's not the same. 

A true "Fast 3G" would output something like this on its results: `Moto G4 - Chrome Canary - 3GFast`

Any chance we can rename all the "Fast 3G" subtitles to "Regular 3G" or "Better 3G"?

Thanks~!

**Comment by addyosmani** [comment]
This is very fair feedback. So the "Fast 3G" times are based on https://www.webpagetest.org/easy (second option in the drop-down) which is "Mobile - Faster 3G". This is a 1.6mbps 3G connection with 300ms of latency and corresponds to the "Mobile 3G" setting in regular WebPageTest.

@housseindjirdeh shall we update those to say "Faster 3G"?

We could probably also include somewhere lower down what these settings correspond to network wise.

**Comment by lukeed** [comment]
Thanks! Very helpful. Much easier than repeatedly ticking all the Advanced settings' checkboxes. 😅

**Comment by housseindjirdeh** [comment]
Thanks @lukeed, agreed I think it makes perfect sense to include the network settings.

@addyosmani It might also be worthwhile to mention that the network settings can easily be obtained using `/easy. Maybe include a link after each setting description?

**Comment by addyosmani** [comment]
SG!
