### ISSUE TITLE
Preact Implementation

### ISSUE THREAD

**Issue by malbernaz** [tastejs/hacker-news-pwas#94]
Hey, I've just made a preact version of HNPWA. Could someone take a look? Thanks!

link:
https://preact-hn.now.sh

lighthouse:
https://www.webpagetest.org/lighthouse.php?test=170710_YP_cb200c6802242f8ad8b7f24e7c916887&run=1

webpagetest (emerging markets): https://www.webpagetest.org/result/170714_B2_63b427aa46eb48b19e51e7374341f1a1/

webpagetest (faster 3g): https://www.webpagetest.org/result/170714_ZD_baecb5715968cd54b7059efe6489eefa/

repository:
https://github.com/malbernaz/preact-hn

**Comment by anubhav7495** [comment]
@malbernaz very nice implementation. Please open a pull request to get your app added.

Check this link for More info: [How to Contribute](https://github.com/tastejs/hacker-news-pwas/blob/master/CONTRIBUTING.md)

Thanks.

**Comment by malbernaz** [comment]
Will do that! Thanks a ton.
